### ISSUE TITLE
运行main.java的时候报错了

### ISSUE THREAD

**Issue by SoulMind01** [DeathWind-sama/Function_Painter_Interpreter#1]
请问大佬有什么头绪吗
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/util/Pair
	at parser.PointProducer.<init>(PointProducer.java:12)
	at parser.ParserMain.<init>(ParserMain.java:23)
	at Main.startMainController(Main.java:13)
	at Main.main(Main.java:36)
Caused by: java.lang.ClassNotFoundException: javafx.util.Pair
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 4 more

**Comment by Ayana-chan** [comment]
jdk问题，你可能用了openjdk导致没有javafx包。可以换一个jdk，或者修改代码以抛弃Pair（我觉得用Pair完全没必要）。抱歉长时间未回复

**Comment by SoulMind01** [comment]
好的谢谢

Ayana-chan ***@***.***> 于 2023年12月19日周二 上午6:31写道：
